### ISSUE TITLE
Font types

### ISSUE THREAD

**Issue by feldrim** [matthewearl/deep-anpr#1]
Fonts.com has a nice [article](https://www.fonts.com/content/learning/fontology/level-1/type-anatomy/type-classifications) about font type classifications. There are 4 categories with 17 sub-categories, which only some of them are used in license plates. So the types you may consider are can be these below.

**Serif Type Styles:** Slab Serif.
**Sans Serif Type Styles:** All four of them.
**Script Type Styles:** None.
**Decorative:** None.

So there are 5 types of fonts to keep in mind. You may consider searching all the states about which is a more specific method. Or, you may consider training the AI with at least 5 types of each 5 classes mentioned above, which is simpler and universial hack.

I tihnk this might be a simple (but not exact) solution for the 2nd drawback in your conclusion.

**Comment by matthewearl** [comment]
It shouldn't be too hard to implement this:  I'm imagining we'd have a fonts/ folder, and then gen.py would just load all fonts into an array and randomly select one at generation time.

There is one possible complication that I can see:  The current code has very basic kerning:  Each character is individually rendered into its own image ahead of time, and then these images are then tiled horizontally.  This scheme works well enough for the UK number plate font, but it might not work so well for other fonts.  A better solution might be to directly render the full license for each image with PIL.ImageDraw.text().

**Comment by matthewearl** [comment]
I've had some success with using the following set of fonts:
  - Slab serif:
    - [Arvo](https://www.fontsquirrel.com/fonts/arvo)
    - [BioRhyme](https://www.fontsquirrel.com/fonts/biorhyme)
    - [BioRhyme Extended](https://www.fontsquirrel.com/fonts/biorhyme-expanded)
    - [Bitstream Vera Serif](https://www.fontsquirrel.com/fonts/Bitstream-Vera-Serif)
    - [Bodonitown](https://www.fontsquirrel.com/fonts/Bodonitown)
    - [Kreon](https://www.fontsquirrel.com/fonts/kreon)
  - Sans serif:
    - [Aaargh](https://www.fontsquirrel.com/fonts/Aaargh)
    - [Aller](https://www.fontsquirrel.com/fonts/Aller)
    - [Amble](https://www.fontsquirrel.com/fonts/amble)
    - [Arimo](https://www.fontsquirrel.com/fonts/arimo)
    - [Bitstream Vera](https://www.fontsquirrel.com/fonts/Bitstream-Vera-Sans)
    - [Capsuula](https://www.fontsquirrel.com/fonts/capsuula)
    - [Cicle](https://www.fontsquirrel.com/fonts/Cicle)
    - [Comme](https://www.fontsquirrel.com/fonts/comme)
    - [Courier Prime Sans](https://www.fontsquirrel.com/fonts/courier-prime-sans)
    - [Norwester](https://www.fontsquirrel.com/fonts/norwester)
    - [Open Sans](https://www.fontsquirrel.com/fonts/open-sans)

The fonts were chosen somewhat arbitrarily from the Font Squirrel lists of slab serif and sans serif fonts.

With these fonts the system seems able to read UK number plates (even though the UK number plate font wasn't provided).  This means it is able to generalize to other fonts, and may be able to read non-UK number plates, however #6 will need fixing before this is possible.

**Comment by quantamc** [comment]
Hello @matthewearl, great project walk  through, I've been tinkering with the code for assembly line product number detection, I changed the font type, changes the generated sequences in gen.py eveything ran Ok but i keep getting this error when running the train.py script, any idea what could be the problem?

`Traceback (most recent call last):
  File "./train.py", line 266, in <module>
    initial_weights=initial_weights)
  File "./train.py", line 174, in train
    digits_loss, presence_loss, loss = get_loss(y, y_)
  File "./train.py", line 132, in get_loss
    [-1, len(common.CHARS)]))
  File "/home/tmalete/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1555, in softmax_cross_entropy_with_logits
    labels, logits)
  File "/home/tmalete/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1510, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
`
