### ISSUE TITLE
Reducing the 99% threshold

### ISSUE THREAD

**Issue by romulofff** [matthewearl/deep-anpr#103]
Hi Matthew, great project! I'm trying to apply it to Brazilian plates, but the detector doesn't work very well to my data. I want to reduce the 99% threshold probability that a plate is present. How (where) can I do that?

Thanks!

**Comment by mazcallu** [comment]
This will do, I think:

Say you want to use a 65% threshold, in detect.py add this:   

 FILTER_PROB = 0.65
    for i, (scaled_im, y_val) in enumerate(zip(scaled_ims, y_vals)):
        for window_coords in numpy.argwhere(y_val[0, :, :, 0] >
                                                       -math.log(1./FILTER_PROB - 1)):

However you will get many more detections and probably false positives.
