### ISSUE TITLE
Provide trained mode

### ISSUE THREAD

**Issue by goodrahstar** [matthewearl/deep-anpr#12]
Hi,
Can someone please provide the trained model. 

Thanks

**Comment by usamaoDATA** [comment]
i too would like access to the trained weights, i dont have the resources to run the training scripts

**Comment by ChadTaljaardt** [comment]
I will train it and provide it for you in a few days 👍

**Comment by ChadTaljaardt** [comment]
Im having issues installing everything required (tensor flow) but i will have it resolved soon.

**Comment by ChadTaljaardt** [comment]
Okay i have a working system out now, training the file today, will upload it in around 7 hours from now 👍

**Comment by goodrahstar** [comment]
Thanks a lot @ChadTaljaardt .. w8ting for your training model.

**Comment by ISKU** [comment]
gj :smile: i want to.

**Comment by ChadTaljaardt** [comment]
Here is the file. 

There was a error when i clicked ctrl + c to end the training after around 180,000 batches, 

Can someone try this and tell me if it works : http://www.mediafire.com/file/j08uh8e4f26u110/weights.npz

**Comment by ChadTaljaardt** [comment]
Got it to work, was using a bad image. 

Here is a result of the model.

![out](https://cloud.githubusercontent.com/assets/13891249/19614412/d5e8c5fa-97ec-11e6-9907-22740578431f.jpg)

**Comment by usamaoDATA** [comment]
thank you for this

**Comment by usamaoDATA** [comment]
can you tell me how long did it take to train and what were the specs of the machine doing the training

**Comment by ChadTaljaardt** [comment]
my specs are: 

AMD Phenom x6 1090T
12GB Ram 
GTX 1070
Ubuntu 16.10
CUDA 8.0
CUDNN 5.1.5

And i think it took like 4-5 hours to converge at around 100,000 but i ran it around 7 hours.

**Comment by goodrahstar** [comment]
Thanks a lot @ChadTaljaardt ... it was really helpful :) 
Cheers (Y)

**Comment by pentateu** [comment]
@ChadTaljaardt the file is no longer available

**Comment by ChadTaljaardt** [comment]
@pentateu Here http://www.mediafire.com/file/j08uh8e4f26u110/weights.npz

**Comment by sxs4337** [comment]
I am unable to load the weights.npz file and get the below error. I have the latest version of numpy with Python 2.7. Any help is appreciated.

Traceback (most recent call last):
  File "detect.py", line 184, in <module>
    f = numpy.load(sys.argv[2])
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 429, in load
    "Failed to interpret file %s as a pickle" % repr(file))
IOError: Failed to interpret file 'weights.npz' as a pickle

**Comment by devika23** [comment]
@ChadTaljaardt  the link for wieghts.npz doesn't seem to be working. can u help?

**Comment by chinmayips** [comment]
HI , @ChadTaljaardt , I am trying to run train , but not on a GPU , but on a normal CPU . 
After about 3 hours , It did not generate any weights.npz. I agree it will not be well trained but it should have at least generated a weights.npz??? Does it generate weights.npz only after it is well trained or maybe there is some other glitch???

**Comment by Abhi001vj** [comment]
@Chinmayi-Prasad  I think it will be generated if you do ctrl-c ,that's what i think from this code snippet from 249 in train.py.

`
           

            249 except KeyboardInterrupt:

            last_weights = [p.eval() for p in params]

            numpy.savez("weights.npz", *last_weights)

            return last_weights`

**Comment by JuanjoLopez** [comment]
What database did you use?

**Comment by chinmayips** [comment]
@JuanjoLopez , The one generated using the generate.py code .

**Comment by prabhjot-singh-gogana** [comment]
Hi @ChadTaljaardt , I really appreciate your affords to create an awesome model. Just want to know can we convert it into .caffemodel or .mlmodel. Thanks in advance

**Comment by QueenJuliaZxx** [comment]
hi,ChadTaljaardt,what is the result come from,is it use the weight file you commented on Oct 22, 2016 ,or another weight file you trained!because I use the weight file you  "ChadTaljaardt commented on Oct 22, 2016 ",it work  still so bad!

**Comment by QueenJuliaZxx** [comment]
hi,ChadTaljaardt,what is the result come from,is it use the weight file you commented on Oct 22, 2016 ,or another weight file you trained!because I use the weight file you "ChadTaljaardt commented on Oct 22, 2016 ",it work still so   @ChadTaljaardt

**Comment by preetj** [comment]
> 
> 
> Here is the file.
> 
> There was a error when i clicked ctrl + c to end the training after around 180,000 batches,
> 
> Can someone try this and tell me if it works : http://www.mediafire.com/file/j08uh8e4f26u110/weights.npz

can u please tell me how to run the project? what to do after downloading the /weights.npz 
where to put it and which files to run after that. Thank you in advance as im new in this thing

**Comment by preetj** [comment]
I'm unable to load 'weights.npz' and having below error. Python version= 3.6.7 and numpy version= 1.16.2. Please, somebody, help me solve this error. Thankyou

Traceback (most recent call last):
  File "detect.py", line 183, in <module>
    f = numpy.load("/weights.npz", allow_pickle=True, fix_imports=True)
  File "/./././././lib/python3.6/site-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/weights.npz'

**Comment by preetj** [comment]
> I'm unable to load 'weights.npz' and having below error. Python version= 3.6.7 and numpy version= 1.16.2. Please, somebody, help me solve this error. Thankyou
> 
> Traceback (most recent call last):
> File "detect.py", line 183, in
> f = numpy.load("/weights.npz", allow_pickle=True, fix_imports=True)
> File "/./././././lib/python3.6/site-packages/numpy/lib/npyio.py", line 415, in load
> fid = open(os_fspath(file), "rb")
> FileNotFoundError: [Errno 2] No such file or directory: '/weights.npz'

@ChadTaljaardt @goodrahstar @usamaoDATA @ISKU @pentateu

**Comment by ChadTaljaardt** [comment]
Hello everyone. 

Sorry that i have not been active in this thread, i haven't used this project in a long time and don't even have the computer i used anymore to be able to train another model. 

Please remember that the project was "experimental" and wasn't designed to match license plates that didn't match a specific format.

**Comment by ChadTaljaardt** [comment]
@preetj Can you show us your directory structure?

**Comment by preetj** [comment]
> @preetj Can you show us your directory structure?

ThankYou so much @ChadTaljaardt for replying.
I found the error just now it was because I extracted the weights.npz folder instead of using the zip file.

**Comment by haha363** [comment]
> > @preetj Can you show us your directory structure?
> 
> ThankYou so much @ChadTaljaardt for replying.
> I found the error just now it was because I extracted the weights.npz folder instead of using the zip file.

Hi @preetj 
I am encountering the same error as you, can you show your code on how you solve this problem? Thanks a lot
