### ISSUE TITLE
Only presence recognition..

### ISSUE THREAD

**Issue by sapeyes** [matthewearl/deep-anpr#17]
I am a follower of your development. I studied whole codes and adapted to my project. 
My objective is only about presence recognition using ConvNets. 
I collected original images of number plate and added real image to training image with your affine transform code. But something is weird that it is not apparent when presence is True.  Sometimes, appropriately scaled and located plate is tagged as False image. I am now considering to improve the guideline of being True for presence. 

You wrote..  min and max scale factors. Also some other factors (rotation, translation) are available. 
I think these parameters should be improved to make presence value more apparent.

**Comment by sapeyes** [comment]
I found that, without plate numbers, the performance of the only presence recognition can be measured very highly with no big variation in data augmentation using affine transform. I tried the presence recognition of Korean license plates, 3x3 filter based (CONV-RELU-POOL)*3+2FC gave me 100% recognition rate if I reduce the variance in data augmentation.

**Comment by sapeyes** [comment]
I added category of plates into training target vector. This caused significant improvement in recognition performance. Now I see 100% recognition rate of Korean plate presence with big variation in data augmentation using affine transfomation. Thanks @matthewearl for your nice insight. It was also really helpful to know network trick from your code to speed up recognition instead of using real window sliding.

**Comment by hungpt297** [comment]
@sapeyes 
Could you share your code? I also want to detect plate only, using real windows sliding is really slow
Thanks for your nice info.

**Comment by sapeyes** [comment]
Window sliding is actually performed by CONVs not FCs in detection part. This trick is well explained in http://cs231n.github.io/convolutional-networks/#convert 

This is implemented in model.py and detect.py. I am using it. 
My code is almost same as this deep-anpr project. I just changed output dimension of his network and.. input image transformation. But almost same.
