### ISSUE TITLE
./train.py error Synology DS1513+ DSM 6.1

### ISSUE THREAD

**Issue by CerBerE67112** [matthewearl/deep-anpr#60]
Need help, thx.

Traceback (most recent call last):
  File "./train.py", line 266, in <module>
    initial_weights=initial_weights)
  File "./train.py", line 174, in train
    digits_loss, presence_loss, loss = get_loss(y, y_)
  File "./train.py", line 132, in get_loss
    [-1, len(common.CHARS)]))
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1555, in softmax_cross_entropy_with_logits
    labels, logits)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1510, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

**Comment by longnguyenduy233** [comment]
This error due to the new version of tensorflow so you should change the line  softmax_cross_entropy_with_logits to "softmax_cross_entropy_with_logits(labels=
                                          tf.reshape(y[:, 1:],
                                                     [-1, len(common.CHARS)]),logits=
                                          tf.reshape(y_[:, 1:],
                                                     [-1, len(common.CHARS)]))"
and the same for sigmoid.

**Comment by CerBerE67112** [comment]
Thx @lovemoon23 
I have done the correction on both... 
it'd seemed working... was in progress  

Receiving just this alert...

> WARNING:tensorflow:From /volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/tensorflow/python/util/tf_should_use.py:170: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
> Instructions for updating:
> Use `tf.global_variables_initializer` instead.

End then it returned

> Killed

an idea why ?

**Comment by longnguyenduy233** [comment]
It's just warning, i don't think it killed. Could you show me a stack trace??

**Comment by CerBerE67112** [comment]
I'd love. Were can I find those traces ?

Maked the changes for the alert and received "Killed"...

```
# Depreciated in new version of tensorflow (https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md#release-0120) 
# init = tf.initialize_all_variables()
# Replaced with
init = tf.global_variables_initializer()
```

**Comment by CerBerE67112** [comment]
I also ran 
`python3 -m trace --count -C . ./train.py`

but did nothing else than returning a 

> Killed

 after +/- 1 min.

**Comment by CerBerE67112** [comment]
Thx @lovemoon23 you did the job.
My server is not strong enough to run a training

`dmesg | grep -E -i -B100 'killed'`

> [1737318.688401] [16606]  1024 16606   903682   250893    1407   121306             0 python3
> [1737319.001678] Out of memory: Kill process 16606 (python3) score 278 or sacrifice child
> [1737325.126753] [16606]  1024 16606   903682   261508    1426   121708             0 python3
> [1737325.432111] Out of memory: Kill process 16606 (python3) score 286 or sacrifice child
> [1737325.440058] Killed process 16606 (python3) total-vm:3614728kB, anon-rss:1046032kB, file-rss:0kB
