### ISSUE TITLE
Variable Length Modifications, Paid Support

### ISSUE THREAD

**Issue by isgursoy** [matthewearl/deep-anpr#63]
Can anybody help me with variable length modifications required for 6-8 chars PL plates? It is urgent; please touch me.

**Comment by ujsyehao** [comment]
you can refer to RNN and LSTM, CRNN can solve it.

**Comment by isgursoy** [comment]
It is an urgent project and we will have fixed price contract with the developer who wants to work on this.

**Comment by ujsyehao** [comment]
@isgursoy OK， this is my email: rawk.vx@gmail.com, I am interested in the urgent project

**Comment by isgursoy** [comment]
Post is open until otherwise stated.

**Comment by ambr89** [comment]
Any information how can make dynamics length of text?
