### ISSUE TITLE
I Did It !

### ISSUE THREAD

**Issue by yayapipi** [matthewearl/deep-anpr#82]
![out](https://user-images.githubusercontent.com/6084519/33796997-7479d356-dd3a-11e7-967e-00905425ca13.png)

Detect.py

**Comment by engahmed1190** [comment]
@yayapipi 
Can you please share knowledge

**Comment by heartfulsong** [comment]
@yayapipi
Can you share your code?

**Comment by wenting521** [comment]
Can you share your code？ 
I did get an error while executing train.py.
(1、AttributeError: Can't pickle local object 'mpgen.<locals>.main'；
2、EOFError: Ran out of input.)
Do you have encountered such problems and hope to get your answers. Thank you very much!

**Comment by crr0306** [comment]
Do you solve it?

**Comment by pendex900x** [comment]
change 

@mpgen to #@mpgen

**Comment by pendex900x** [comment]
change

@mpgen to #@mpgen
